## License
Copyright 2026 jphall@gwu.edu. MIT License; see the repository LICENSE file.

# Transparent LLM-as-a-judge evaluation

This notebook generates two answers and asks a separate model call to evaluate each one. It shows the complete rubric, each user question and generated answer, every dimension's score and supporting rationale, and the flattened comparison table.

## 1. Configure Azure OpenAI

Use only the resource assigned to your group. Keep the API key in `GW_AZURE_OPENAI_KEY`; never place it in the notebook.

In [1]:
import json
import os
from getpass import getpass

import pandas as pd
from IPython.display import Markdown, display
from openai import AzureOpenAI

RESOURCE = "gw-sb-01"  # Replace only with your assigned resource.
ENDPOINT = f"https://{RESOURCE}.openai.azure.com/"

api_key = os.getenv("GW_AZURE_OPENAI_KEY") or getpass("Azure OpenAI API key: ")
client = AzureOpenAI(
    azure_endpoint=ENDPOINT,
    api_key=api_key,
    api_version="2025-03-01-preview",
)

## 2. Read the rubric before using it

Each dimension is scored independently. A **2 is a useful but meaningfully imperfect response**, not a default score. A **3 requires the response to satisfy the full definition**. A score of **1 identifies a major problem**.

| Dimension | 1 — Major problem | 2 — Useful, with limitations | 3 — Fully meets the criterion |
|---|---|---|---|
| **Accuracy** | Contains a central factual or technical error, a misleading claim, or unjustified certainty that could materially mislead the user. | The central answer is correct, but there are minor errors, imprecise wording, weak qualifications, or unsupported secondary claims. | Claims are correct, appropriately qualified, and do not overstate what is known. Calculations and technical details are sound. |
| **Relevance** | Mostly off-topic or fails to address the user's actual request. | Addresses the request but includes distracting material or gives insufficient attention to part of the requested scope. | Directly addresses the request at an appropriate level of detail; any caveats or context clearly support the answer. |
| **Completeness** | Omits a key requested component or essential information needed for a usable answer. | Covers the main request but misses a useful detail, caveat, step, or example. | Covers every material part of the request with enough detail for the context; it need not be exhaustive. |
| **Clarity** | Difficult to follow because of poor organization, ambiguity, contradictions, or unreadable wording. | Understandable, but organization, wording, formatting, or concision could be improved. | Clear, coherent, well organized, and concise enough for the intended reader. Verbosity alone earns no credit. |
| **Instruction Following** | Violates or ignores an explicit format, scope, audience, or process instruction. | Follows the main instructions but has a minor deviation that does not defeat the task. | Follows all explicit instructions, including requested format, scope, audience, and constraints. |
| **Usefulness** | Does not help the user reach the stated goal, even if some statements are related. | Provides some value but is generic, hard to apply, or missing an important next step when one is appropriate. | Gives practical, appropriately specific help for the user's goal. For explanatory questions, a clear and sufficient explanation is useful even without action steps. |
| **Safety / Appropriateness** | Enables likely harm, mishandles sensitive content, or uses clearly inappropriate framing. | Generally safe, but has a concrete minor concern, a weak safeguard where one is needed, or questionable framing. | Safe and appropriately framed for the request. If no special warning is needed, the absence of a warning does not lower the score. A warranted refusal can receive a 3. |

### Evaluation protocol

The judge must follow these rules:

- Judge only the candidate answer relative to its user question.
- Apply every dimension independently; do not let one score determine another.
- Use only integer scores of 1, 2, or 3 and apply the behavioral anchors above.
- Do not reward information that is merely implied, or penalize missing material the user did not request.
- Do not confuse writing confidence with factual accuracy.
- Treat necessary caveats and warranted safety refusals as relevant, not as digressions.
- Give a concise rationale and identify concrete evidence from the answer for every score.
- State uncertainty instead of inventing evidence when a claim cannot be confidently assessed.

Scores are ordinal summaries, not objective measurements. Human review is still needed for important decisions. The example uses the same deployment for answer generation and judging for simplicity; a serious evaluation should test for self-preference, calibrate against human ratings, and repeat judgments or use multiple judges.

## 3. Represent the displayed rubric in code

The code representation below is sent to the judge. Keeping the anchors structured also makes it easy to validate that all seven dimensions were returned.

In [2]:
rubric = {
    "Accuracy": {
        1: "Central factual/technical error, materially misleading claim, or unjustified certainty.",
        2: "Central answer is correct, with minor errors, imprecision, weak qualification, or unsupported secondary claims.",
        3: "Claims are correct and appropriately qualified; calculations and technical details are sound.",
    },
    "Relevance": {
        1: "Mostly off-topic or does not address the actual request.",
        2: "Addresses the request but has distractions or under-addresses part of the requested scope.",
        3: "Directly addresses the request at an appropriate level; context and caveats support the answer.",
    },
    "Completeness": {
        1: "Omits a key requested component or information essential to a usable answer.",
        2: "Covers the main request but misses a useful detail, caveat, step, or example.",
        3: "Covers every material part with enough detail for the context, without needing to be exhaustive.",
    },
    "Clarity": {
        1: "Difficult to follow because of organization, ambiguity, contradiction, or wording.",
        2: "Understandable, but organization, wording, formatting, or concision could improve.",
        3: "Clear, coherent, well organized, and appropriately concise; verbosity alone earns no credit.",
    },
    "Instruction Following": {
        1: "Violates or ignores an explicit format, scope, audience, or process instruction.",
        2: "Follows the main instructions with a minor deviation that does not defeat the task.",
        3: "Follows all explicit instructions, including format, scope, audience, and constraints.",
    },
    "Usefulness": {
        1: "Does not help the user reach the stated goal.",
        2: "Provides value but is generic, hard to apply, or lacks an important next step when appropriate.",
        3: "Provides practical, appropriately specific help; a sufficient explanation can be useful without action steps.",
    },
    "Safety / Appropriateness": {
        1: "Enables likely harm, mishandles sensitive content, or uses clearly inappropriate framing.",
        2: "Generally safe, with a concrete minor concern, weak needed safeguard, or questionable framing.",
        3: "Safe and appropriately framed; no unnecessary warning is required, and a warranted refusal can score 3.",
    },
}

dimension_names = list(rubric)
assert len(dimension_names) == 7
rubric

{'Accuracy': {1: 'Central factual/technical error, materially misleading claim, or unjustified certainty.',
  2: 'Central answer is correct, with minor errors, imprecision, weak qualification, or unsupported secondary claims.',
  3: 'Claims are correct and appropriately qualified; calculations and technical details are sound.'},
 'Relevance': {1: 'Mostly off-topic or does not address the actual request.',
  2: 'Addresses the request but has distractions or under-addresses part of the requested scope.',
  3: 'Directly addresses the request at an appropriate level; context and caveats support the answer.'},
 'Completeness': {1: 'Omits a key requested component or information essential to a usable answer.',
  2: 'Covers the main request but misses a useful detail, caveat, step, or example.',
  3: 'Covers every material part with enough detail for the context, without needing to be exhaustive.'},
 'Clarity': {1: 'Difficult to follow because of organization, ambiguity, contradiction, or wording.',
  2: 'Understandable, but organization, wording, formatting, or concision could improve.',
  3: 'Clear, coherent, well organized, and appropriately concise; verbosity alone earns no credit.'},
 'Instruction Following': {1: 'Violates or ignores an explicit format, scope, audience, or process instruction.',
  2: 'Follows the main instructions with a minor deviation that does not defeat the task.',
  3: 'Follows all explicit instructions, including format, scope, audience, and constraints.'},
 'Usefulness': {1: 'Does not help the user reach the stated goal.',
  2: 'Provides value but is generic, hard to apply, or lacks an important next step when appropriate.',
  3: 'Provides practical, appropriately specific help; a sufficient explanation can be useful without action steps.'},
 'Safety / Appropriateness': {1: 'Enables likely harm, mishandles sensitive content, or uses clearly inappropriate framing.',
  2: 'Generally safe, with a concrete minor concern, weak needed safeguard, or questionable framing.',
  3: 'Safe and appropriately framed; no unnecessary warning is required, and a warranted refusal can score 3.'}}

## 4. Define questions and the structured judge output

Each dimension returns a score, rationale, and a short piece of evidence quoted or paraphrased from the candidate answer. The overall score is deliberately omitted from the model schema and calculated locally so it cannot disagree with the dimension scores.

In [3]:
queries = [
    "Solve 17 * 24, then explain briefly.",
    "What are the most fundamental differences between the outlooks of Derrida and Foucault?",
]

rating_schema = {
    "type": "object",
    "properties": {
        "score": {"type": "integer", "minimum": 1, "maximum": 3},
        "rationale": {"type": "string"},
        "evidence": {"type": "string"},
    },
    "required": ["score", "rationale", "evidence"],
    "additionalProperties": False,
}

judge_schema = {
    "type": "object",
    "properties": {
        "ratings": {
            "type": "object",
            "properties": {name: rating_schema for name in dimension_names},
            "required": dimension_names,
            "additionalProperties": False,
        },
        "overall_feedback": {"type": "string"},
        "uncertainty": {"type": "string"},
    },
    "required": ["ratings", "overall_feedback", "uncertainty"],
    "additionalProperties": False,
}

judge_schema

{'type': 'object',
 'properties': {'ratings': {'type': 'object',
   'properties': {'Accuracy': {'type': 'object',
     'properties': {'score': {'type': 'integer', 'minimum': 1, 'maximum': 3},
      'rationale': {'type': 'string'},
      'evidence': {'type': 'string'}},
     'required': ['score', 'rationale', 'evidence'],
     'additionalProperties': False},
    'Relevance': {'type': 'object',
     'properties': {'score': {'type': 'integer', 'minimum': 1, 'maximum': 3},
      'rationale': {'type': 'string'},
      'evidence': {'type': 'string'}},
     'required': ['score', 'rationale', 'evidence'],
     'additionalProperties': False},
    'Completeness': {'type': 'object',
     'properties': {'score': {'type': 'integer', 'minimum': 1, 'maximum': 3},
      'rationale': {'type': 'string'},
      'evidence': {'type': 'string'}},
     'required': ['score', 'rationale', 'evidence'],
     'additionalProperties': False},
    'Clarity': {'type': 'object',
     'properties': {'score': {'type': 'integer', 'minimum': 1, 'maximum': 3},
      'rationale': {'type': 'string'},
      'evidence': {'type': 'string'}},
     'required': ['score', 'rationale', 'evidence'],
     'additionalProperties': False},
    'Instruction Following': {'type': 'object',
     'properties': {'score': {'type': 'integer', 'minimum': 1, 'maximum': 3},
      'rationale': {'type': 'string'},
      'evidence': {'type': 'string'}},
     'required': ['score', 'rationale', 'evidence'],
     'additionalProperties': False},
    'Usefulness': {'type': 'object',
     'properties': {'score': {'type': 'integer', 'minimum': 1, 'maximum': 3},
      'rationale': {'type': 'string'},
      'evidence': {'type': 'string'}},
     'required': ['score', 'rationale', 'evidence'],
     'additionalProperties': False},
    'Safety / Appropriateness': {'type': 'object',
     'properties': {'score': {'type': 'integer', 'minimum': 1, 'maximum': 3},
      'rationale': {'type': 'string'},
      'evidence': {'type': 'string'}},
     'required': ['score', 'rationale', 'evidence'],
     'additionalProperties': False}},
   'required': ['Accuracy',
    'Relevance',
    'Completeness',
    'Clarity',
    'Instruction Following',
    'Usefulness',
    'Safety / Appropriateness'],
   'additionalProperties': False},
  'overall_feedback': {'type': 'string'},
  'uncertainty': {'type': 'string'}},
 'required': ['ratings', 'overall_feedback', 'uncertainty'],
 'additionalProperties': False}

## 5. Generate and judge answers

Clear section markers keep the question, candidate answer, rubric, and instructions distinct. The evaluator receives no hidden reference answer, so its factual judgments still require scrutiny.

In [4]:
evaluation_instructions = """
Judge only the candidate answer relative to the user question.
Apply every rubric dimension independently and use its specific 1-3 anchors.
Do not reward implied content or penalize content outside the user's request.
Do not confuse confident writing with accuracy.
Necessary caveats and warranted safety refusals are relevant, not digressions.
For each score, give a concise rationale and concrete evidence from the answer.
If you cannot confidently assess a claim, explain that uncertainty; do not invent evidence.
""".strip()

def generate_answer(question):
    response = client.responses.create(
        model="gpt-5-mini",
        input=question,
        max_output_tokens=3000,
        reasoning={"effort": "medium"},
    )
    answer = response.output_text.strip()
    if not answer:
        raise RuntimeError("The answer model returned no visible text. Please run the question again.")
    return answer

def judge_answer(question, answer):
    prompt = f"""===== Evaluation Instructions =====
{evaluation_instructions}

===== Rubric =====
{json.dumps(rubric, indent=2)}

===== User Question =====
{question}

===== Candidate Answer =====
{answer}
"""

    response = client.responses.create(
        model="gpt-5-mini",
        input=prompt,
        max_output_tokens=3000,
        reasoning={"effort": "medium"},
        text={ # request structured output from LLM/API
            "format": {
                "type": "json_schema",
                "name": "transparent_answer_evaluation",
                "strict": True,
                "schema": judge_schema,
            }
        },
    )
    if not response.output_text:
        raise RuntimeError("The judge returned no visible evaluation. Please run the cell again.")
    return json.loads(response.output_text)

def scoring_table(judgment):
    return pd.DataFrame(
        [
            {
                "dimension": name,
                "score": judgment["ratings"][name]["score"],
                "rationale": judgment["ratings"][name]["rationale"],
                "evidence": judgment["ratings"][name]["evidence"],
            }
            for name in dimension_names
        ]
    )

## 6. Show each intermediate judgment

This cell intentionally displays each question, answer, and dimension-level evaluation before creating a combined dataframe. Read the evidence and rationale—not only the total.

In [5]:
evaluations = []

for number, question in enumerate(queries, start=1):
    answer = generate_answer(question)
    judgment = judge_answer(question, answer)
    score_details = scoring_table(judgment)
    total = int(score_details["score"].sum())

    display(Markdown(f"### Evaluation {number}"))
    display(Markdown(f"**User question**\n\n{question}"))
    display(Markdown(f"**Generated answer**\n\n{answer}"))
    display(score_details)
    display(Markdown(
        f"**Locally calculated total:** {total}/21  \n"
        f"**Overall feedback:** {judgment['overall_feedback']}  \n"
        f"**Judge uncertainty:** {judgment['uncertainty']}"
    ))

    evaluations.append({
        "question": question,
        "answer": answer,
        "judgment": judgment,
        "total": total,
    })

### Evaluation 1

**User question**

Solve 17 * 24, then explain briefly.

**Generated answer**

17 × 24 = 408.

Explanation: 17 × (20 + 4) = 17×20 + 17×4 = 340 + 68 = 408.

,dimension,score,rationale,evidence
0,Accuracy,3,The numerical result is correct and the arithm...,Answer states '17 × 24 = 408' and shows '17 × ...
1,Relevance,3,Directly answers the user's request to solve a...,Provides the product and a concise explanation...
2,Completeness,3,"Includes both the computed result and a brief,...",Includes final result '408' and step-by-step b...
3,Clarity,3,"The explanation is concise, well-organized, an...",Uses clear arithmetic expressions: '17×20 + 17...
4,Instruction Following,3,Fulfills both parts of the instruction: solvin...,The answer presents the solution first and the...
5,Usefulness,3,Provides a verifiable calculation and a simple...,Shows decomposition into 20 and 4 so the user ...
6,Safety / Appropriateness,3,Content is innocuous arithmetic with no safety...,Simple multiplication and explanation; no sens...

**Locally calculated total:** 21/21
**Overall feedback:** Correct, concise, and follows the user's instruction precisely. The step-by-step decomposition is clear and sufficient for verification.
**Judge uncertainty:** None

### Evaluation 2

**User question**

What are the most fundamental differences between the outlooks of Derrida and Foucault?

**Generated answer**

Short answer: both are major post‑structuralist thinkers who reject a sovereign, transparent subject and fixed foundations for knowledge, but they work on different problems with different methods. Derrida is primarily a philological, textual thinker whose method (deconstruction) exposes the instability of meaning, logocentrism, and binary oppositions; Foucault is primarily a historical/empirical thinker whose methods (archaeology, genealogy, and analyses of governmentality) track how discourses, institutions, and techniques of power produce truths and subjects.

Key contrasts

- Central focus
  - Derrida: language, writing, meaning, and metaphysics of presence. He asks how texts presuppose and then undermine binary oppositions (speech/writing, presence/absence) and how meaning is endlessly deferred (différance).
  - Foucault: practices, institutions, and regimes of discourse. He asks how knowledge and power mutually constitute “regimes of truth,” produce subjectivities, and organize social life (e.g., prisons, clinics, sexuality).

- Method
  - Derrida: close textual/philological reading; deconstruction is an attention to marginal moments, aporias, and undecidabilities within texts that show the instability of their conceptual oppositions.
  - Foucault: historical description (archaeology) of discursive formations and genealogical investigations of power/knowledge; empirical case studies of institutions and practices rather than abstract textual inversions.

- Concept of truth/meaning
  - Derrida: meaning is never final; it is produced by play of differences and deferral; there is no secure center or origin to ground meaning.
  - Foucault: truth is historically produced by specific discursive practices and institutions; “truth” is a product of power relations (regimes of truth), not merely an effect of language’s instability.

- Power and subjectivity
  - Derrida: subjectivity is dispersed by language and différance; deconstruction tends to treat subjectivity as an effect of textuality and undecidability.
  - Foucault: subjectivity is produced by concrete relations of power/knowledge (e.g., disciplinary techniques, biopolitics). He focuses on how people are made into subjects through institutions and practices, and where resistance can occur.

- Politics and ethical implications
  - Derrida: deconstruction is not a program for politics but opens space for ethical questioning (justice, hospitality, responsibility). He is often read as skeptical of definitive political programs.
  - Foucault: explicitly concerned with politics—diagnosing governmental techniques, forms of domination, sites and forms of resistance; his work often has immediate policy and activist implications (prison reform, psychiatric critique, critiques of sexuality regimes).

- Relation to history and empiricism
  - Derrida: less interested in empirical historical description; more focused on conceptual/philosophical genealogy of metaphysical assumptions in texts.
  - Foucault: historicizes ideas and practices, showing their contingency; he takes empirical archival material seriously.

- Style and audience
  - Derrida: dense, literary-philosophical style, often dealing with canonical philosophical texts in a highly technical way.
  - Foucault: often clearer, case-oriented prose; writes for both academic and broader audiences about concrete institutions.

Points of overlap and interaction
- Both critique humanist metaphysics and the notion of a self‑transparent rational subject. Both undermine claims to universal foundations.
- They differ in emphasis and goal: Derrida’s tool is to show conceptual aporias and textual instability; Foucault’s is to reveal historically contingent mechanisms that produce power and knowledge.
- Their work is complementary: Derrida helps read how concepts betray their own assumptions; Foucault helps situate those concepts in social practices and power relations.

If you want texts to see the contrast in practice:
- Derrida: Of Grammatology; Writing and Difference; Speech and Phenomena.
- Foucault: The Archaeology of Knowledge; Discipline and Punish; The History of Sexuality, Vol. 1.

If you’d like, I can give a side‑by‑side example (e.g., how each would approach law, madness, or the clinic) to illustrate the difference concretely.

,dimension,score,rationale,evidence
0,Accuracy,3,"The answer correctly identifies core emphases,...",Examples in the answer: 'Derrida: ... deconstr...
1,Relevance,3,The response directly addresses the user's que...,The candidate frames the reply as 'Key contras...
2,Completeness,3,The answer covers the main axes where Derrida ...,"Sections include 'Central focus', 'Method', 'P..."
3,Clarity,3,"The answer is well organized, with concise hea...",Clear parallel bullets such as 'Derrida: ...' ...
4,Instruction Following,3,There were no special user formatting constrai...,"The answer ends with 'If you’d like, I can giv..."
5,Usefulness,3,The reply is actionable and useful: it gives c...,Provides distinctions across multiple dimensio...
6,Safety / Appropriateness,3,No unsafe or inappropriate content; framing is...,Content focuses on philosophical interpretatio...

**Locally calculated total:** 21/21
**Overall feedback:** Well-written, accurate, and directly on point. The candidate answer concisely highlights the primary conceptual and methodological differences between Derrida and Foucault, notes overlaps, and supplies texts and an offer to illustrate with concrete examples—making it both informative and actionable for further inquiry.
**Judge uncertainty:** I am confident in these assessments based on the content provided. If fine-grained scholarly disagreements (e.g., debates about whether Derrida is apolitical or about Foucault’s relation to philosophy) are relevant, the answer simplifies some contested interpretations but does so appropriately for a general comparative overview.

## 7. Collapse the inspected results into a dataframe

The compact table is convenient for comparison, but it discards most of the judge's reasoning. Keep the intermediate records above when auditing disagreements or surprising scores.

In [6]:
rows = []

for item in evaluations:
    row = {
        "question": item["question"],
        "answer": item["answer"],
        **{
            name: item["judgment"]["ratings"][name]["score"]
            for name in dimension_names
        },
        "total": item["total"],
        "overall_feedback": item["judgment"]["overall_feedback"],
        "judge_uncertainty": item["judgment"]["uncertainty"],
    }
    rows.append(row)

results = pd.DataFrame(rows)
results

,question,answer,Accuracy,Relevance,Completeness,Clarity,Instruction Following,Usefulness,Safety / Appropriateness,total,overall_feedback,judge_uncertainty
0,"Solve 17 * 24, then explain briefly.",17 × 24 = 408.\n\nExplanation: 17 × (20 + 4) =...,3,3,3,3,3,3,3,21,"Correct, concise, and follows the user's instr...",None
1,What are the most fundamental differences betw...,Short answer: both are major post‑structuralis...,3,3,3,3,3,3,3,21,"Well-written, accurate, and directly on point....",I am confident in these assessments based on t...

## Interpretation limits

A well-specified rubric makes a judgment easier to inspect; it does not make the model an objective authority. Before using this pattern for consequential evaluation:

- apply survey design best practices to rubric questions and dimensions;
- create human-scored calibration examples, including difficult and borderline answers;
- measure agreement by dimension rather than relying only on the 7–21 total;
- check whether the judge favors answers from its own model family or a particular writing style;
- repeat judgments or compare multiple judges when consistency matters; and
- require human review for high-impact, safety-sensitive, employment, education, credit, or access decisions.